/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppExploreRouteImport } from './routes/_app/explore'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppUploadRouteImport } from './routes/_app/upload'
import { Route as AppUHandleRouteImport } from './routes/_app/u.$handle'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDiscordCallbackRouteImport } from './routes/api/discord/callback'
import { Route as ApiDiscordInteractionsRouteImport } from './routes/api/discord/interactions'
import { Route as ApiDiscordStartRouteImport } from './routes/api/discord/start'
import { Route as ApiMediaKindIdRouteImport } from './routes/api/media/$kind/$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppUHandleRoute = AppUHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscordCallbackRoute = ApiDiscordCallbackRouteImport.update({
  id: '/api/discord/callback',
  path: '/api/discord/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscordInteractionsRoute = ApiDiscordInteractionsRouteImport.update({
  id: '/api/discord/interactions',
  path: '/api/discord/interactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscordStartRoute = ApiDiscordStartRouteImport.update({
  id: '/api/discord/start',
  path: '/api/discord/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaKindIdRoute = ApiMediaKindIdRouteImport.update({
  id: '/api/media/$kind/$id',
  path: '/api/media/$kind/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/explore': typeof AppExploreRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/upload': typeof AppUploadRoute
  '/u/$handle': typeof AppUHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/discord/callback': typeof ApiDiscordCallbackRoute
  '/api/discord/interactions': typeof ApiDiscordInteractionsRoute
  '/api/discord/start': typeof ApiDiscordStartRoute
  '/api/media/$kind/$id': typeof ApiMediaKindIdRoute
}
export interface FileRoutesByTo {
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/explore': typeof AppExploreRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/upload': typeof AppUploadRoute
  '/': typeof AppIndexRoute
  '/u/$handle': typeof AppUHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/discord/callback': typeof ApiDiscordCallbackRoute
  '/api/discord/interactions': typeof ApiDiscordInteractionsRoute
  '/api/discord/start': typeof ApiDiscordStartRoute
  '/api/media/$kind/$id': typeof ApiMediaKindIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/explore': typeof AppExploreRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/upload': typeof AppUploadRoute
  '/_app/': typeof AppIndexRoute
  '/_app/u/$handle': typeof AppUHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/discord/callback': typeof ApiDiscordCallbackRoute
  '/api/discord/interactions': typeof ApiDiscordInteractionsRoute
  '/api/discord/start': typeof ApiDiscordStartRoute
  '/api/media/$kind/$id': typeof ApiMediaKindIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/login'
    | '/admin'
    | '/explore'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/upload'
    | '/u/$handle'
    | '/api/auth/$'
    | '/api/discord/callback'
    | '/api/discord/interactions'
    | '/api/discord/start'
    | '/api/media/$kind/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/datenschutz'
    | '/impressum'
    | '/login'
    | '/admin'
    | '/explore'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/upload'
    | '/'
    | '/u/$handle'
    | '/api/auth/$'
    | '/api/discord/callback'
    | '/api/discord/interactions'
    | '/api/discord/start'
    | '/api/media/$kind/$id'
  id:
    | '__root__'
    | '/_app'
    | '/datenschutz'
    | '/impressum'
    | '/login'
    | '/_app/admin'
    | '/_app/explore'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/upload'
    | '/_app/'
    | '/_app/u/$handle'
    | '/api/auth/$'
    | '/api/discord/callback'
    | '/api/discord/interactions'
    | '/api/discord/start'
    | '/api/media/$kind/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDiscordCallbackRoute: typeof ApiDiscordCallbackRoute
  ApiDiscordInteractionsRoute: typeof ApiDiscordInteractionsRoute
  ApiDiscordStartRoute: typeof ApiDiscordStartRoute
  ApiMediaKindIdRoute: typeof ApiMediaKindIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/upload': {
      id: '/_app/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/u/$handle': {
      id: '/_app/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof AppUHandleRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discord/callback': {
      id: '/api/discord/callback'
      path: '/api/discord/callback'
      fullPath: '/api/discord/callback'
      preLoaderRoute: typeof ApiDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discord/interactions': {
      id: '/api/discord/interactions'
      path: '/api/discord/interactions'
      fullPath: '/api/discord/interactions'
      preLoaderRoute: typeof ApiDiscordInteractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discord/start': {
      id: '/api/discord/start'
      path: '/api/discord/start'
      fullPath: '/api/discord/start'
      preLoaderRoute: typeof ApiDiscordStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$kind/$id': {
      id: '/api/media/$kind/$id'
      path: '/api/media/$kind/$id'
      fullPath: '/api/media/$kind/$id'
      preLoaderRoute: typeof ApiMediaKindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppExploreRoute: typeof AppExploreRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUploadRoute: typeof AppUploadRoute
  AppIndexRoute: typeof AppIndexRoute
  AppUHandleRoute: typeof AppUHandleRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppExploreRoute: AppExploreRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUploadRoute: AppUploadRoute,
  AppIndexRoute: AppIndexRoute,
  AppUHandleRoute: AppUHandleRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDiscordCallbackRoute: ApiDiscordCallbackRoute,
  ApiDiscordInteractionsRoute: ApiDiscordInteractionsRoute,
  ApiDiscordStartRoute: ApiDiscordStartRoute,
  ApiMediaKindIdRoute: ApiMediaKindIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
